version: '3.5'

# Start    | docker-compose up -d
# Stop     | docker-compose stop
# Update   | docker-compose pull
# Logs     | docker-compose logs --tail=25 -f
# Terminal | docker-compose exec photoprism bash
# Help     | docker-compose exec photoprism photoprism help
# Config   | docker-compose exec photoprism photoprism config
# Reset    | docker-compose exec photoprism photoprism reset
# Backup   | docker-compose exec photoprism photoprism backup -a -i
# Restore  | docker-compose exec photoprism photoprism restore -a -i
# Index    | docker-compose exec photoprism photoprism index
# Reindex  | docker-compose exec photoprism photoprism index -f
# Import   | docker-compose exec photoprism photoprism import

services:
    
  caddy_gen:
    container_name: caddy_gen
    image: "wemakeservices/caddy-gen:latest"
    ports:
      - 80:80
      - 443:443
    environment:
      CADDY_SNIPPET: /etc/caddy/caddy.snippet
    depends_on:
      - heimdall
      - nextcloud
      - pgadmin
      - photoprism
      - prometheus
      - grafana
      - secret
      - ihatemoney
      - vault
      - gokapi
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # needs socket to read events
      - caddy_data:/data
      - caddy_etc:/etc/caddy
      - caddy_config:/config
    restart: unless-stopped
    
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    ports:
      - 3535:80
      - 3536:443
    volumes:
      - heimdall:/config # change into www/.env APP_URL=your.domain.com
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    labels:
      virtual.host: ${DOMAIN}
      virtual.port: 80
      virtual.tls-email: ${TLS_EMAIL}
    
# For update nextcloud delete images and pull
  nextcloud:
    build:
      context: ./nextcloud/
      args:
        NEXTCLOUD_IMAGE: nextcloud:28
    container_name: nextcloud
    ports:
      - 5000:80
    environment:
      - POSTGRES_HOST=host.docker.internal:5432
      - POSTGRES_DB=${NEXTCLOUD_POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=3072M
    depends_on:
      - postgres
      - redis
    volumes:
      - nextcloud_html:/var/www/html
      - nextcloud_php:/usr/local/etc/php
      - C:\\docker-caches\nextcloud\preview:/var/www/html/data/appdata_ocah283m7og5/preview
      - M:\\nextcloud\FixFever:/var/www/html/data/FixFever/files
      - M:\\nextcloud\Elya:/var/www/html/data/Elya/files
      - M:\\nextcloud\Boris:/var/www/html/data/Boris/files
      - M:\\nextcloud\Marina:/var/www/html/data/Marina/files
      - M:\\nextcloud\trashbin\FixFever:/var/www/html/data/FixFever/files_trashbin/files
      - M:\\nextcloud\trashbin\Elya:/var/www/html/data/Elya/files_trashbin/files
      - M:\\nextcloud\trashbin\Boris:/var/www/html/data/Boris/files_trashbin/files
      - M:\\nextcloud\trashbin\Marina:/var/www/html/data/Marina/files_trashbin/files
    restart: unless-stopped
    labels:
      virtual.host: nextcloud.${DOMAIN}
      virtual.port: 80
      virtual.tls-email: ${TLS_EMAIL}
      
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${NEXTCLOUD_POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped
    
  nextcloud_cron:
    image: nextcloud:28
    container_name: nextcloud_cron
    volumes_from:
      - nextcloud:rw
    entrypoint: /cron.sh
    user: 0:0
    depends_on:
      - postgres
    restart: unless-stopped
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - POSTGRES_DB=${NEXTCLOUD_POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    labels:
      virtual.host: pgadmin.${DOMAIN}
      virtual.port: 80
      virtual.tls-email: ${TLS_EMAIL}
    
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - 2342:2342
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}          
      PHOTOPRISM_AUTH_MODE: "password"               # authentication mode (public, password)
      PHOTOPRISM_SITE_URL: "https://photoprism.fixfever.keenetic.pro/"  # public server URL incl http:// or https:// and /path, :port is optional
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_LOG_LEVEL: "info"                   # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "true"                    # do not modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "true"              # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"            # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW files
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW files (reduces performance)
      PHOTOPRISM_JPEG_QUALITY: 85                    # a higher value increases the quality and file size of JPEG images and thumbnails (25-100)
      PHOTOPRISM_DETECT_NSFW: "true"                 # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: mariadb:3306     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: ${MARIADB_USER}         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: ${MARIADB_PASSWORD}       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""                # meta site description
      PHOTOPRISM_SITE_AUTHOR: ""                     # meta site author
      PHOTOPRISM_WORKERS: 6                          # maximum NUMBER of indexing workers, default depends on the number of physical cores
    working_dir: "/photoprism" # do not change or remove
    volumes:
      - photoprism:/photoprism
      - C:\\docker-caches\photoprism\cache:/photoprism/storage/cache
      - C:\\docker-caches\photoprism\sidecar:/photoprism/storage/sidecar
      - M:\\nextcloud\FixFever\Фото:/photoprism/originals
      # "/host/folder:/photoprism/folder"                # Example
      #- "~/Pictures:/photoprism/originals"               # Original media files (DO NOT REMOVE)
      # - "/example/family:/photoprism/originals/family" # *Additional* media folders can be mounted like this
      # - "~/Import:/photoprism/import"                  # *Optional* base folder from which files can be imported to originals
      #- "./storage:/photoprism/storage"                  # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)
    restart: unless-stopped
    labels:
      virtual.host: photoprism.${DOMAIN}
      virtual.port: 2342
      virtual.tls-email: ${TLS_EMAIL}
      
  mariadb:
    image: mariadb:10.8
    container_name: mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
    restart: unless-stopped
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - '--storage.tsdb.retention.time=3y'
    ports:
      - 9090:9090
    volumes:
      - prometheus_etc:/etc/prometheus
      - H:\docker-volumes\prometheus:/prometheus
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default
    restart: unless-stopped
    labels:
      virtual.host: prometheus.${DOMAIN}
      virtual.port: 9090
      virtual.tls-email: ${TLS_EMAIL}
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - grafana_lib:/var/lib/grafana
      - grafana_provisioning:/etc/grafana/provisioning/
    environment:
      TZ: "Europe/Moscow"
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: false
    networks:
      - default
    restart: unless-stopped
    labels:
      virtual.host: grafana.${DOMAIN}
      virtual.port: 3000
      virtual.tls-email: ${TLS_EMAIL}
      
  secret:
    image: ghcr.io/tethik/burn-after-reading/burn-after-reading:1.5.1
    container_name: secret
    ports:
      - 5035:80
    volumes:
      - secret:/opt/data
    environment:     
      - MAX_CONTENT_LENGTH=134217728
      - BURN_DATA_PATH=/opt/data/
      - BURN_MAX_STORAGE=1024
    restart: unless-stopped
    labels:
      virtual.host: secret.${DOMAIN}
      virtual.port: 80
      virtual.tls-email: ${TLS_EMAIL}
      
  ihatemoney:
    image: ihatemoney/ihatemoney:latest
    container_name: ihatemoney
    ports:
      - 8000:8000
    volumes:
      - ihatemoney_database:/database
      - ihatemoney_etc:/etc/ihatemoney
    environment:
      - ACTIVATE_ADMIN_DASHBOARD=True
      - ACTIVATE_DEMO_PROJECT=False
      - ADMIN_PASSWORD=${IHATEMONEY_ADMIN_PASSWORD}
      - ALLOW_PUBLIC_PROJECT_CREATION=True
      - BABEL_DEFAULT_TIMEZONE='Europe/Moscow'
      - SECRET_KEY=somekey
      - PORT=8000
    restart: unless-stopped
    labels:
      virtual.host: ihatemoney.${DOMAIN}
      virtual.port: 8000
      virtual.tls-email: ${TLS_EMAIL}
      
  vault:
    image: vaultwarden/server:latest
    container_name: vault
    ports:
      - "3012:3012"
      - "8282:80"
    volumes:
      - vault:/data
    environment:
      - WEBSOCKET_ENABLED=true
      - LOG_FILE=/data/logs.txt
      - ADMIN_TOKEN=${VAULT_ADMIN_TOKEN}
      - DOMAIN=https://vault.fixfever.keenetic.pro
      - SIGNUPS_ALLOWED=true
    restart: unless-stopped
    labels:
      virtual.host: vault.${DOMAIN}
      virtual.port: 80
      virtual.tls-email: ${TLS_EMAIL}

  gokapi:
    image: f0rc3/gokapi:latest
    container_name: gokapi
    ports:
      - 53842:53842
    volumes:
      - gokapi_config:/app/config
      - gokapi_data:/app/data
    restart: unless-stopped
    labels:
      virtual.host: gokapi.${DOMAIN}
      virtual.port: 53842
      virtual.tls-email: ${TLS_EMAIL}

volumes:

  caddy_config:
    external: true
  caddy_data:
    external: true
  caddy_etc:
    external: true
    
  heimdall:
    external: true
 
  nextcloud_html:
    external: true
  nextcloud_php:
    external: true
    
  postgres_data:
    external: true
    
  redis_data:
    external: true
    
  pgadmin:
    external: true
    
  photoprism:
    external: true
    
  mariadb:
    external: true
    
  prometheus_etc:
    external: true
    
  grafana_lib:
    external: true
  grafana_provisioning:
    external: true
    
  secret:
    external: true
    
  ihatemoney_database:
    external: true
    
  ihatemoney_etc:
    external: true
    
  vault:
    external: true
    
  gokapi_config:
    external: true
  gokapi_data:
    external: true
    external: true