version: '3.5'

services:
    
  quake:
    image: treyyoder/quakejs:latest
    container_name: quake
    ports:
      - '8081:80'
      - '27960:27960'
    environment:
      - HTTP_PORT=8081
    volumes:
      - quake:/quakejs/base
    restart: unless-stopped 
    labels:
      virtual.host: quake.${DOMAIN}
      virtual.port: 80
    
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      MAX_MEMORY: 3G
    volumes:
      - minecraft:/data
    restart: unless-stopped
    labels:
      virtual.host: minecraft.${DOMAIN}
      virtual.port: 25565
 
volumes:
 
  quake:
    external: true
    
  minecraft:
    external: true