version: '3.5'

services:
    
  quake:
    image: treyyoder/quakejs:latest
    container_name: quake
    ports:
      - '8081:80'
      - '27960:27960'
    environment:
      - HTTP_PORT=8081
    volumes:
      - C:\docker-volumes\quake:/quakejs/base
    restart: unless-stopped 
    labels:
      virtual.host: quake.${DOMAIN}
      virtual.port: 80
      
  valheim: 
    image: ghcr.io/lloesche/valheim-server:latest
    container_name: valheim
    cap_add:
      - sys_nice
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    volumes: 
      - C:\docker-volumes\valheim:/config
      - H:\backups\valheim:/config/backups
    env_file:
      - C:\docker-volumes\valheim\valheim.env
    stop_grace_period: 2m
    restart: unless-stopped
    
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      MAX_MEMORY: 3G
    volumes:
      - C:\docker-volumes\minecraft:/data
    restart: unless-stopped
    labels:
      virtual.host: minecraft.${DOMAIN}
      virtual.port: 25565