services:

  quake:
    image: treyyoder/quakejs:latest
    container_name: quake
    ports:
      - '8081:80'
      - '27960:27960'
    environment:
      - HTTP_PORT=8081
    volumes:
      - quake:/quakejs/base
    restart: unless-stopped 

volumes:
  quake:
    external: true